# Generated by Django 5.2.7 on 2025-11-05 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('short_content', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_date'],
            },
        ),
    ]
