# Generated by Django 5.2.7 on 2025-12-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappoint',
            options={'permissions': [('view_all_maps', 'Может просматривать все карты')], 'verbose_name': 'Точка на карте', 'verbose_name_plural': 'Точки на карте'},
        ),
    ]
