# Generated by Django 5.2.7 on 2025-11-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Kompanija Vendtime d.o.o', max_length=200, verbose_name='Юридическое название')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.TextField(blank=True, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon_class', models.CharField(max_length=50, verbose_name='Класс иконки')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('main', 'Основной'), ('secondary', 'Дополнительный'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10, verbose_name='Тип телефона')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
    ]
