# Generated by Django 5.2.7 on 2025-11-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_type',
            field=models.CharField(choices=[('main', 'Основной'), ('secondary', 'Дополнительный'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='main', max_length=10, verbose_name='Тип телефона'),
        ),
    ]
