# Generated by Django 5.2.7 on 2025-11-05 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('water', 'Вода'), ('grabber', 'Хватайка')], max_length=10, verbose_name='Тип автомата')),
                ('quantity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Количество')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('building', models.CharField(max_length=20, verbose_name='Номер строения')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация или пожелания', verbose_name='Комментарий')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_date'],
            },
        ),
    ]
